pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Express source code checked out'
            }
        }

        stage('Install & Test') {
            steps {
                sh '''
                cd frontend
                npm install
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                cd frontend
                pm2 delete express-app || true
                pm2 start app.js --name express-app
                pm2 save
                '''
            }
        }
    }

    post {
        success {
            echo 'Express deployed successfully'
        }
        failure {
            echo 'Express deploy failed'
        }
    }
}

