version: '3.8'
services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: node-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped
